name: Java Validate

on:
  push:
  workflow_call:

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: test-gihub-app/github-workflow-template

      - uses: test-gihub-app/github-workflow-template/.github/actions/action-test@main